RECORD_TYPE_OSD = 0x01
RECORD_TYPE_HOME = 0x02
RECORD_TYPE_GIMBAL = 0x03
RECORD_TYPE_RC = 0x04
RECORD_TYPE_CUSTOM = 0x05
RECORD_TYPE_DEFORM = 0x06
RECORD_TYPE_CENTER_BATTERY = 0x07
RECORD_TYPE_SMART_BATTERY = 0x08
RECORD_TYPE_APP_TIP = 0x09
RECORD_TYPE_APP_WARN = 0x0A
RECORD_TYPE_RC_GPS = 0x0B
RECORD_TYPE_RC_DEBUG = 0x0C
RECORD_TYPE_RECOVER = 0x0D
RECORD_TYPE_APP_GPS = 0x0E
RECORD_TYPE_FIRMWARE = 0x0F
RECORD_TYPE_OFDM_DEBUG = 0x10
RECORD_TYPE_VISION_GROUP = 0x11
RECORD_TYPE_VISION_WARN = 0x12
RECORD_TYPE_MC_PARAM = 0x13
RECORD_TYPE_APP_OPERATION = 0x14
RECORD_TYPE_APP_SER_WARN = 0x18
RECORD_TYPE_JPEG = 0x39
RECORD_TYPE_OTHER = 0xFE

JPEG_SOI_BYTE = 0xD8




